// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIhy2w3Dj5Z9hmS-dKoHw0gmP9x7gdETc',
    appId: '1:652046343209:web:962b88735b6601037d9038',
    messagingSenderId: '652046343209',
    projectId: 'mindcare-project',
    authDomain: 'mindcare-project.firebaseapp.com',
    storageBucket: 'mindcare-project.appspot.com',
    measurementId: 'G-DDM6NBXFXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXUXmRaHgDhOIT7WgYTCzwwntGp-yKFYY',
    appId: '1:652046343209:android:f9dd9936ffe9c3d67d9038',
    messagingSenderId: '652046343209',
    projectId: 'mindcare-project',
    storageBucket: 'mindcare-project.appspot.com',
  );
}
